import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Shivam",
      email: "shivam@singh.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "user",
      email: "user@singh.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 110,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 20,
      brand: "nike",
      rating: 4.0,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.2,
      numReviews: 16,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pant",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 12,
      brand: "Nike",
      rating: 4.6,
      numReviews: 12,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pant",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 18,
      brand: "Puma",
      rating: 4.9,
      numReviews: 16,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pant",
      image: "/images/p6.jpg",
      price: 55,
      countInStock: 18,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 22,
      description: "high quality product",
    },
  ],
};

export default data;
