export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCESS = "ORDER_CREATE_SUCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDERD_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCESS = "ORDERD_DETAILS_SUCESS";
export const ORDER_DETAILS_FAIL = "ORDERD_DETAILS_FAIL";
